// Bun APIs (Bun.spawnSync, import.meta.dir) don't resolve for the
// TypeScript checker since this is a build-only script.
// oxlint-disable-next-line typescript/ban-ts-comment
// @ts-nocheck
/**
 * @file Build script for self-contained Vessel executable.
 *
 * Produces a single binary that contains the Bun runtime, all server code,
 * and all client-side static assets (CSS, JS, fonts, images). The only
 * external requirement at runtime is a `data/` directory for the SQLite
 * database and session JSONL files.
 *
 * Steps:
 *   1. Run `vite build` (adapter-bun) to produce the standard build output
 *   2. Scan `build/client/` for every static asset
 *   3. Auto-generate `build/standalone/assets.ts` with `import ... with { type: "file" }`
 *      for each asset and a URL→path mapping
 *   4. Compile `src/standalone/entry.ts` + the generated assets into a standalone binary
 *
 * Usage:
 *   bun run scripts/build-standalone.ts
 *
 * @see src/standalone/entry.ts — the persistent entry point that loads the
 *   generated asset module and serves embedded assets in compiled mode.
 */

import { join } from "path";
import {
    existsSync,
    mkdirSync,
    readdirSync,
    statSync,
    writeFileSync,
} from "node:fs";

const BUILD_DIR = "build";
const CLIENT_DIR = join(BUILD_DIR, "client");
const STANDALONE_DIR = join(BUILD_DIR, "standalone");
const ENTRY_POINT = "src/standalone/entry.ts";
const ASSETS_MODULE = join(STANDALONE_DIR, "assets.ts");
const OUTPUT_BINARY = join(STANDALONE_DIR, "vessel");

// --- Step 1: Vite build ---

console.log("[1/4] Running vite build (adapter-bun)...");
const viteResult = Bun.spawnSync(["bun", "--bun", "vite", "build"], {
    cwd: import.meta.dir.replace(/\/scripts$/, ""),
    stdout: "inherit",
    stderr: "inherit",
});
if (viteResult.exitCode !== 0) {
    console.error("vite build failed — aborting.");
    process.exit(1);
}

// Create standalone dir AFTER vite build (vite may clean build/)
mkdirSync(STANDALONE_DIR, { recursive: true });

// --- Step 2: Collect files ---

console.log("[2/4] Scanning client assets...");

/**
 * Collect all file paths under a directory using depth-first search.
 *
 * @param rootDir - Directory to scan
 * @returns Array of file paths relative to rootDir
 */
function collectFiles(rootDir: string): string[] {
    if (!existsSync(rootDir)) return [];
    const files: string[] = [];
    const stack: { dir: string; prefix: string }[] = [
        { dir: rootDir, prefix: "" },
    ];
    while (stack.length > 0) {
        const { dir, prefix } = stack.pop()!;
        for (const entry of readdirSync(dir)) {
            const fullPath = join(dir, entry);
            const relPath = prefix ? `${prefix}/${entry}` : entry;
            if (statSync(fullPath).isDirectory()) {
                stack.push({ dir: fullPath, prefix: relPath });
            } else {
                files.push(relPath);
            }
        }
    }
    return files;
}

const clientFiles = collectFiles(CLIENT_DIR);
const staticFiles = collectFiles("static");

console.log(
    `  Found ${clientFiles.length} client files + ${staticFiles.length} static files`,
);

// --- Step 3: Generate assets.ts ---

console.log("[3/4] Generating build/standalone/assets.ts...");

const importLines: string[] = [];
const mappingEntries: string[] = [];

// Client assets: URL path = /${relPath}
for (let i = 0; i < clientFiles.length; i++) {
    const relPath = clientFiles[i];
    const varName = `a${i}`;
    // Relative from build/standalone/assets.ts → build/client/${relPath}
    importLines.push(
        `import ${varName} from "../client/${relPath}" with { type: "file" };`,
    );
    mappingEntries.push(`  assetMap["/${relPath}"] = ${varName};`);
}

// Static files: URL path = /${relPath}
for (let i = 0; i < staticFiles.length; i++) {
    const relPath = staticFiles[i];
    const varName = `s${i}`;
    // Relative from build/standalone/assets.ts → static/${relPath}
    importLines.push(
        `import ${varName} from "../../static/${relPath}" with { type: "file" };`,
    );
    mappingEntries.push(`  assetMap["/${relPath}"] = ${varName};`);
}

const assetsModuleContent = `/**
 * @file Auto-generated embedded asset map for standalone Vessel binary.
 *
 * Generated by scripts/build-standalone.ts — DO NOT EDIT.
 * Each import uses Bun's \`with { type: "file" }\` to embed the file
 * into the compiled binary's virtual filesystem.
 *
 * @see src/standalone/entry.ts — the entry point that loads this module.
 */

${importLines.join("\n")}

/**
 * Maps URL paths to embedded file paths in the $bunfs virtual filesystem.
 * Used by src/standalone/entry.ts to serve static assets without sirv.
 */
export const assetMap: Record<string, string> = {};
${mappingEntries.join("\n")}
`;

writeFileSync(ASSETS_MODULE, assetsModuleContent, "utf-8");
console.log(
    `  Generated ${ASSETS_MODULE} (${clientFiles.length + staticFiles.length} asset imports)`,
);

// --- Step 4: Compile ---

console.log("[4/4] Compiling standalone binary...");
const projectRoot = import.meta.dir.replace(/\/scripts$/, "");

const compileResult = Bun.spawnSync(
    [
        "bun",
        "build",
        "--compile",
        "--target=bun",
        "--minify",
        join(projectRoot, ENTRY_POINT),
        "--outfile",
        join(projectRoot, OUTPUT_BINARY),
    ],
    {
        cwd: projectRoot,
        stdout: "inherit",
        stderr: "inherit",
    },
);

if (compileResult.exitCode !== 0) {
    console.error("Compilation failed — aborting.");
    process.exit(1);
}

// --- Report ---

const binaryStat = statSync(join(projectRoot, OUTPUT_BINARY));
const mb = (binaryStat.size / 1024 / 1024).toFixed(1);

console.log(`
✅ Standalone Vessel binary built successfully!

   Binary:  ${OUTPUT_BINARY} (${mb} MB)
   Assets:  ${clientFiles.length + staticFiles.length} embedded

   Usage:
     mkdir -p data && ./${OUTPUT_BINARY}

   The binary only needs a data/ directory (for the SQLite DB and
   session JSONL files). All server code, client assets, the Bun
   runtime, and native addons are embedded in the binary.
`);
